### ISSUE TITLE
Support for ESI/alternative responses

### ISSUE THREAD

**Issue by vivace-io** [zKillboard/RedisQ#10]
Currently, RedisQ sends Killmails in the CREST format (which is awesome, by the way), however with it getting phased out in the long term, it would be nice to consider a way of providing ESI responses instead of CREST in a way that would not break applications in the mean time.

I'm wondering if it would be feasable to do one of two things:

- (A) Support a URL parameter `format=esi` which would instruct RedisQ to reply with ESI (and the appended `zkb` JSON field) or...
- (B) Support a URL parameter `format=zkb` which simply returns the `zkb` JSON field, with the addition of the kill ID in that field.

The first seems like it would add a bit of extra overhead on Redis if you stored the ESI format along side CREST's, or converted CREST to ESI. The second idea seems slightly more doable, especially considering there exists no rate limit for ESI so the leg work could easily be left to the client in retrieving the data.

What are your thoughts?

**Comment by cvweiss** [comment]
Since the killID and the hash are included in all killmails being sent to RedisQ, you can easily pull the ESI version of the kill. When zkill switches 100% to ESI (e.g. when all killmail endpoints are completed) then RedisQ will see some changes. Until then I'm holding out.
