### ISSUE TITLE
Inconsistent package format?

### ISSUE THREAD

**Issue by randomic** [zKillboard/RedisQ#11]
So one of my apps which uses RedisQ started throwing a bunch of errors. I checked it out and it seemed like the package format had changed. No problem, I rewrote part of it to compensate.

I kept on getting the odd error. It seemed like some of the packages arriving were still coming in the old format. Okay no problem, I wrote a bit of logic to handle both formats.

Now it seems that my app is getting all packages in the "old" format.

However, when I point my browser at RedisQ, the packages I see are in the 'new' format. I captured some examples:

What my app sees: https://hastebin.com/eduyawuhol.json
What I see in my browser: https://hastebin.com/honineyepa.json

Is there any reason why this might be happening?

**Comment by cvweiss** [comment]
No crest data is being sent through redisq anymore, hell I don't even call the crestserver for killmails anymore, not to mention the code that puts it in that crest format is gone now.

Only thing I can think of is maybe your app is processing some older data?

**Comment by randomic** [comment]
Turns out I'm terrible and was overlooking the line where I put crest data in. My bad.
