### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by Slazanger** [zKillboard/RedisQ#12]
in the FAQ it states that no rate limit is applied and to hit it as hard as you like; however even with a 100ms pause when pulling kills i occasionally get a 429 (Too Many Requests) response.

What is the maximum limit ?  I dont want to overload the server however also dont want to get behind in the tool.

Thanks,

**Comment by cvweiss** [comment]
If you're getting a 429 that means you have too many connections to RedisQ from your IP, a limit of one connection at a time is allowed. If you think that isn't true, then you most likely have something that isn't fully closing a connection properly.

**Comment by jameson2011** [comment]
Remember that Redisq only sees a public IP address, and will only serve one connection from that IP. So if you're working behind a NAT or other shared network where multiple machines connect to Redisq, then all those machines less 1 will get 429s. You might also get 429s if you're on a VPN, again if some other machine is connecting to Redisq.

**Comment by Slazanger** [comment]
I've been keeping an eye on it and haven't managed to repro it again;   Thanks for the responses.

**Comment by cvweiss** [comment]
> Remember that Redisq only sees a public IP address, and will only serve one connection from that IP. So if you're working behind a NAT or other shared network where multiple machines connect to Redisq, then all those machines less 1 will get 429s. You might also get 429s if you're on a VPN, again if some other machine is connecting to Redisq.

Yup, and I even provide a workaround for this situation in the documentation.
