### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by kalgecin** [zKillboard/RedisQ#14]
I've encountered the 429 rate limit. There was a bug in the code that didn't close the connections it seems. I've read through the issues, and you seem to talk about documentation. The only documentation regarding redisq requests i've seen is the README in this project. How do i go about unblocking my bot? Is there some ban timeout i have to wait out?

**Comment by ErikKalkoken** [comment]
I am also occasional getting 429 "too many requests" with my app.

The reason apparently is this ([source](https://github.com/zKillboard/RedisQ/blob/49a506a05f78ef79743aeaba28fa155316d2dc97/public/banned.html)):

> You can only have one request to listen.php in flight at any time, otherwise you will generate a too many requests error (429). If you have too many of these errors your IP will be automatically banned.

I think it would be great to also have that info in the README / FAQ.

**Comment by cvweiss** [comment]
The documentation does not state that it supports multiple calls. The error itself is a good explanation.

I had no idea this issue was here/opened, otherwise I would have closed it in 2018. Sorry for the delay.
