### ISSUE TITLE
Service does not collects KMs between calls

### ISSUE THREAD

**Issue by seb-odessa** [zKillboard/RedisQ#15]
I am expecting that service will collect all killmails between API invocations.

I've used '?queueID=54689e7ff0b3cebfa1' id for each call but have not received more than one record in response.

This looks like a defect.

And the second question.
Does there are possible to configure redisq.zkillboard.com api to send response in short format (id, hash), like the history API (zkillboard.com/api/history/)

**Comment by cvweiss** [comment]
Each call returns one killmail, no more. To get more killmails execute more calls.
