### ISSUE TITLE
fitted isk doesn't match value on website

### ISSUE THREAD

**Issue by madelynnblue** [zKillboard/RedisQ#17]
I hit the redisQ endpoint and saw:

```
{
    "package":
        {
            "killID": 93719959,
            "killmail":
                {...},
            "zkb":
                {
                    "awox": false,
                    "destroyedValue": 380199332.7,
                    "droppedValue": 18083376.8,
                    "fittedValue": 371963885.27,
                    "hash": "551c7df74dbfdad8841b0f0947766f25ab149bb7",
                    "href":
                        "https://esi.evetech.net/v1/killmails/93719959/551c7df74dbfdad8841b0f0947766f25ab149bb7/",
                    "labels": ["cat:6", "2+", "npc", "highsec"],
                    "locationID": 50006549,
                    "npc": true,
                    "points": 1,
                    "solo": false,
                    "totalValue": 398282709.5
                }
        }
}
```

The [website](93688137) lists the fitted value as `63,479,570.62 ISK`, much lower than the 371M isk listed in the redisq result. I've looked around but have not been able to determine the cause of this difference. Can you explain it? Do I need to do another api call to zkillboard to get the corrected value?

**Comment by cvweiss** [comment]
While the numbers not matching are an issue, this isn't a RedisQ issue. This is the website itself having one valued stored (what gets sent through RedisQ) and displaying another value on the webpage.

Closing this issue here since it isn't RedisQ's fault.

**Comment by madelynnblue** [comment]
Is there a way to get the number on the website? Should I open a new issue in the other repo?

**Comment by cvweiss** [comment]
@mjibson Yes please!
