### ISSUE TITLE
Package contains invalid urls for item/ship icons

### ISSUE THREAD

**Issue by randomic** [zKillboard/RedisQ#2]
For example,
```JSON
"shipType":{
    "id_str":"29336",
    "href":"https://crest-tq.eveonline.com/inventory/types/29336/",
    "id":29336,
    "name":"Scythe Fleet Issue",
    "icon":{
        "href":"http://imageserver.eveonline.com/Type/29336_128.png"
    }
}
```
The href given for the ship icon leads to a 404 since the EVE Online Image Server inventory type icons are only available in 64x64 and in 32x32.

The icon should lead to `"http://imageserver.eveonline.com/Type/29336_64.png"`

**Comment by cvweiss** [comment]
Anything that's wrong with the information in CREST is coming straight from CCP. zKillboard doesn't do anything to modify the mail.

**Comment by randomic** [comment]
I thought that might be the case, thanks!
