### ISSUE TITLE
Kill order doesn't make any sense

### ISSUE THREAD

**Issue by shibdib** [zKillboard/RedisQ#3]
figured it out

**Comment by cvweiss** [comment]
> Perhaps I'm missing something but just refreshing that link I see the killID bounce all over the place. Shouldn't it in theory every time I refresh go up until I reach the current one at which point a refresh will return null til a new kill is posted?

Since the original issue was edited I'm going to add this here. There is no ordering to the kills, as zKillboard gets kills in a random order and sends them to RedisQ which then disperses them in a random order too. There is no order here, only chaos.
