### ISSUE TITLE
Can I subscribe to just my pilot's / character's / alliance's killmails?

### ISSUE THREAD

**Issue by shibdib** [zKillboard/RedisQ#4]
That FAQ.. is this in the works yet?

**Comment by cvweiss** [comment]
> Not at this time. I went with stupidly simple simplicity when I made this and didn't bother with any code for filters and/or subscriptions. You can easily write the code on your end to filter the killmails to your preferences.

**Comment by shibdib** [comment]
Yup saw that but the readme is 9 months old and u word it like it's coming eventually :P

**Comment by cvweiss** [comment]
There are no plans for implementation of filters and/or subscriptions at this time.
