### ISSUE TITLE
Feature Request - Another way to keep track of subsequent requests (other than IP)

### ISSUE THREAD

**Issue by MattCopenhaver** [zKillboard/RedisQ#5]
I want to use this with AWS Lambda on a schedule, but I don't think the same IP will be used with Lambda.

Would it be a good idea to add another way to track this, maybe with a query parameter or something?

Alternatively, I may try to manually set one of the headers that are tracked in https://github.com/zKillboard/RedisQ/blob/master/src/IP.php.

**Comment by cvweiss** [comment]
Already there:

https://github.com/zKillboard/RedisQ/blob/master/public/listen.php#L5

**Comment by cvweiss** [comment]
Hrm, although that only works with POST

**Comment by regner** [comment]
Any reason that feature only works with POST?

**Comment by cvweiss** [comment]
I think I did it accidentally in the hope I would one day annoy an ex-CCP developer.

**Comment by cvweiss** [comment]
That should do it, if you run into any issues let me know please :)
