### ISSUE TITLE
RedisQ down?

### ISSUE THREAD

**Issue by ErikKalkoken** [zKillboard/RedisQ#6]
Hi
I have been using RedisQ for my services, but since 2017-01-05 19:10:10 he is no providing killmails, but returning NULL all the time.

I tried from different machines. Always the same result.

The result of any request is:
```
{
      package : null
}
```

But we great if this issue could be investigates.
Cheers,
Erik

**Comment by cvweiss** [comment]
working again, redis decided to not be responsive :/

**Comment by ErikKalkoken** [comment]
thanks a lot for the quick response :-)
