### ISSUE TITLE
Faction Information

### ISSUE THREAD

**Issue by shadowcodex** [zKillboard/RedisQ#7]
Is it possible for you to include faction information as well?

Using it here: https://shadowcodex.github.io/fw-eve-map/

**Comment by cvweiss** [comment]
Faction entities are already included on killmails. What information are you looking for?

**Comment by shadowcodex** [comment]
I'm looking for if the player is in faction warfare, which faction are they fighting for. 

Maybe I just don't know the right path to the data?

**Comment by cvweiss** [comment]
Ah, if a character is fighting for a faction it should show on the killmail, or you can check their character sheet.

For example, the victim here is in a faction: https://crest-tq.eveonline.com/killmails/60862378/8d6bac38e7dc52fd2b0de7254626dd0bc2ca8c81/

**Comment by shadowcodex** [comment]
Ahhhh ok, thank you.
