### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by shadowcodex** [zKillboard/RedisQ#9]
I am hitting the endpoint once every second, and wanted to do it that quick to grab as many kill mails as I can in a timely fashion.

However I noticed that when there is no killmail to report I get a CORS error... So the console starts filling up. I've tried setting `crossDomain` to `true` in the jQuery ajax call, but that isn't working.

Is there something configured incorrectly on the redisq server that is causing the null response to have a limiting `Access-Control-Allow-Origin` header?

**Comment by shadowcodex** [comment]
Looked at source, and looks like ya'll are doing it right... Must be something with jquery...

**Comment by shadowcodex** [comment]
Possible solution?

`header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);`

Instead of using `*` which isn't supported by some browsers apparently you can use the above to specifically allow the calling origin domain.

**Comment by cvweiss** [comment]
It seems odd that "Access-Control-Allow-Origin: *" works when there is a killmail but doesn't work when there isn't a killmail as the header is passed no matter what. I'm hesitant to modify the code on what is normally pretty standard and accepted on modern browsers.

**Comment by shadowcodex** [comment]
aye it does seem strange...

**Comment by cvweiss** [comment]
Are you still experiencing issues?

**Comment by shadowcodex** [comment]
Yeah it still errors out on null responses, so freaking strange...

**Comment by shadowcodex** [comment]
If you want to see it in action here it is: http://map.cryrs.org/

IDK how to quite do it differently.

**Comment by cvweiss** [comment]
Looking at your source code you have too many requests at once, even with setInterval at 1000ms and a ttw of 1 second, it isn't going to be perfect and there's a good chance of overlap. I wouldn't call redisq until your previous request is completely finished processing. This will remove your 429s

**Comment by shadowcodex** [comment]
I added a lockout on the interval based on whether or not an ajax function was still running. Seems to be working on my dev site, will deploy it with next release.

Thanks!
